### ISSUE TITLE
What‘s the meanings of kshot and kquery?

### ISSUE THREAD

**Issue by Mrxuefei** [dragen1860/MAML-TensorFlow#1]
Hellp,thank you for your contribution.I have some confusion about the definition of some paramaters.n-way means we sample from n classes, k-shot means we sample k examples from each class(Am I right?),but I don't understand what is "k-query"?

**Comment by dragen1860** [comment]
Hi, your comprehension towards n-way and k-shot is right.
k-query means the number of image to be sampled for testing per class.
For instance of 5 way 1 shot, when we trained on 5 images of different categories, such as cat, dog, ...,  we want to test the accuracy. We need to sample K-query * 5way images to get more precise accuracy. For MAML, the k-query=15, which means we need to sample 15 images per class, namely 80 images in total to compute the accuracy.
Hope it helps.

**Comment by Mrxuefei** [comment]
Thank you！Now I understand.
