### ISSUE TITLE
for regression?

### ISSUE THREAD

**Issue by ucasiggcas** [dragen1860/MAML-TensorFlow#5]
Dear,

Thanks for your project,

but I can't reproduce the author's [regression about sine wave](https://github.com/cbfinn/maml),

Could you help me,Please?
If you share the MAML for Regression,it will be great.
Thanks

**Comment by dragen1860** [comment]
sry, but currently i not working on this field. And i did not implemented the sine part before. But if you understand the code of cnn, you will feel much easier to complete your target.
